image:
  repository: YOUR_DOCKER_IMAGE_REPO    # ← עדכן לריפו התמונה (Docker Hub/GHCR)
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 5000   # אם האפליקציה מאזינה על 5000
