apiVersion: v1
kind: Pod
metadata:
  name: apple-orders-pod
  labels:
    app: apple-orders
spec:
  containers:
    - name: apple-orders-container
      image: idanga41/apple-orders-app:v1
      ports:
        - containerPort: 5000
