apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-orders
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apple-orders
  template:
    metadata:
      labels:
        app: apple-orders
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
